// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	repos "test/internal/app/module1/domain/repos"

	mock "github.com/stretchr/testify/mock"
)

// DetailRepository is an autogenerated mock type for the DetailRepository type
type DetailRepository struct {
	mock.Mock
}

// FindDetailById provides a mock function with given fields: ID
func (_m *DetailRepository) FindDetailById(ID uint64) *repos.DetailRecord {
	ret := _m.Called(ID)

	var r0 *repos.DetailRecord
	if rf, ok := ret.Get(0).(func(uint64) *repos.DetailRecord); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repos.DetailRecord)
		}
	}

	return r0
}
