hooks:
  # hook scripts
  pre-commit:
    - make clean check
  pre-push:
    - make test
  commit-msg:
    - husky lint-commit

# list staged files do some pre-process and git add
lint-staged:
  "*.go":
    - gofmt -l -w

# commit msg rule only support conventionalcommits
lint-commit:
  # could check if this exists
  email: "^(.+@gmail.com|.+@qq.com)$"
  # optional custom types check regex
  types: "^(feat|fix|build|chore|ci|docs|perf|refactor|revert|style|test)$"
  # optional header check regex
  header: ^(?P<type>\w+)(\((?P<scope>[\w/.-]+)\))?(?P<breaking>!)?:( +)?(?P<header>.+)
