app:
  name: test
http:
  mode: release
  host: localhost
  port: 8081
db:
  enable: false
  url: "postgres://root:root@localhost:5432/test?sslmode=disable"
  migrations:
    dir: "/resources/db/migrations"
redis:
  enable: false
  network: "tcp"
  url: "localhost:6379"
log:
  filename: /tmp/details.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
telemetry:
  enable: true
  serviceName: test
  endpoint: "localhost:4317"
  insecure: true


